name: Deploy to Tailcall

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy on tailcall
      uses: tailcallhq/tailcall-deploy/.github/actions/deploy-action@main
      with:
        file-path: 'clevertap/demo.graphql'
